server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html dashboard.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the Backend Service
    location /auth/ {
        proxy_pass http://todo-backend-service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /todos {
        proxy_pass http://todo-backend-service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
